// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mmopb.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace mmopb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinGame_req
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinGame_ack
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRoom_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public string name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRoom_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int PlayerNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRoom_fin
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoom_req
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoom_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int gender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewRoom_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int PlayerNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectRoom_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectRoom_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int gender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectRoom_err
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewPlayerJoin_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public string name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Chat_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public string chat { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Chat_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public string chat { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoom_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoom_ack
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLeaveRoom_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public string name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomDelete_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RefreshRoomInfo_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int PlayerNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReturnToHomePage_ack
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReturnButton_req
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CheckTime_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float LocalTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CheckTime_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public float LocalTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TimeIsOK_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGame_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public float StartDelay { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetPosition_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Vector2 position { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetPosition_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Vector2 position { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserActor_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public Vector2 position { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long LifeState { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Action action { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserActor_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public Vector2 position { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long LifeState { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Action action { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector2
    {
        [global::ProtoBuf.ProtoMember(1)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Action
    {
        [global::ProtoBuf.ProtoMember(1)]
        public long jump { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long walk { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long attack { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MaskCheck_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool state { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Vector2 position { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MaskCheck_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool state { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Vector2 position { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyCheck_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool state { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int KeyID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyCheck_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool state { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int KeyID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CalculatorResultChange_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int cal_1 { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int cal_2 { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int cal_3 { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int cal_4 { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int cal_5 { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int cal_6 { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CalculatorResultChange_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int cal_1 { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int cal_2 { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int cal_3 { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int cal_4 { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int cal_5 { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int cal_6 { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BookStateChange_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public bool state { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BookStateChange_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public bool state { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwitchStateChange_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int state { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwitchStateChange_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int state { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UmberllaCheck_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int gender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UmberllaCheck_ack
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int gender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameIsOver_req
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int RoomID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameIsOver_ack
    {
    }

}

public class ILRuntime_mmopb
{
    static ILRuntime_mmopb()
    {

        //Initlize();

    }
    public static void Initlize()
    {

        ProtoBuf.PType.RegisterType("mmopb.JoinGame_req", typeof(mmopb.JoinGame_req));
        ProtoBuf.PType.RegisterType("mmopb.JoinGame_ack", typeof(mmopb.JoinGame_ack));
        ProtoBuf.PType.RegisterType("mmopb.GetRoom_req", typeof(mmopb.GetRoom_req));
        ProtoBuf.PType.RegisterType("mmopb.GetRoom_ack", typeof(mmopb.GetRoom_ack));
        ProtoBuf.PType.RegisterType("mmopb.GetRoom_fin", typeof(mmopb.GetRoom_fin));
        ProtoBuf.PType.RegisterType("mmopb.CreateRoom_req", typeof(mmopb.CreateRoom_req));
        ProtoBuf.PType.RegisterType("mmopb.CreateRoom_ack", typeof(mmopb.CreateRoom_ack));
        ProtoBuf.PType.RegisterType("mmopb.NewRoom_ack", typeof(mmopb.NewRoom_ack));
        ProtoBuf.PType.RegisterType("mmopb.SelectRoom_req", typeof(mmopb.SelectRoom_req));
        ProtoBuf.PType.RegisterType("mmopb.SelectRoom_ack", typeof(mmopb.SelectRoom_ack));
        ProtoBuf.PType.RegisterType("mmopb.SelectRoom_err", typeof(mmopb.SelectRoom_err));
        ProtoBuf.PType.RegisterType("mmopb.NewPlayerJoin_ack", typeof(mmopb.NewPlayerJoin_ack));
        ProtoBuf.PType.RegisterType("mmopb.Chat_req", typeof(mmopb.Chat_req));
        ProtoBuf.PType.RegisterType("mmopb.Chat_ack", typeof(mmopb.Chat_ack));
        ProtoBuf.PType.RegisterType("mmopb.LeaveRoom_req", typeof(mmopb.LeaveRoom_req));
        ProtoBuf.PType.RegisterType("mmopb.LeaveRoom_ack", typeof(mmopb.LeaveRoom_ack));
        ProtoBuf.PType.RegisterType("mmopb.PlayerLeaveRoom_ack", typeof(mmopb.PlayerLeaveRoom_ack));
        ProtoBuf.PType.RegisterType("mmopb.RoomDelete_ack", typeof(mmopb.RoomDelete_ack));
        ProtoBuf.PType.RegisterType("mmopb.RefreshRoomInfo_ack", typeof(mmopb.RefreshRoomInfo_ack));
        ProtoBuf.PType.RegisterType("mmopb.ReturnToHomePage_ack", typeof(mmopb.ReturnToHomePage_ack));
        ProtoBuf.PType.RegisterType("mmopb.ReturnButton_req", typeof(mmopb.ReturnButton_req));
        ProtoBuf.PType.RegisterType("mmopb.CheckTime_req", typeof(mmopb.CheckTime_req));
        ProtoBuf.PType.RegisterType("mmopb.CheckTime_ack", typeof(mmopb.CheckTime_ack));
        ProtoBuf.PType.RegisterType("mmopb.TimeIsOK_req", typeof(mmopb.TimeIsOK_req));
        ProtoBuf.PType.RegisterType("mmopb.StartGame_req", typeof(mmopb.StartGame_req));
        ProtoBuf.PType.RegisterType("mmopb.SetPosition_req", typeof(mmopb.SetPosition_req));
        ProtoBuf.PType.RegisterType("mmopb.SetPosition_ack", typeof(mmopb.SetPosition_ack));
        ProtoBuf.PType.RegisterType("mmopb.UserActor_req", typeof(mmopb.UserActor_req));
        ProtoBuf.PType.RegisterType("mmopb.UserActor_ack", typeof(mmopb.UserActor_ack));
        ProtoBuf.PType.RegisterType("mmopb.Vector2", typeof(mmopb.Vector2));
        ProtoBuf.PType.RegisterType("mmopb.Action", typeof(mmopb.Action));
        ProtoBuf.PType.RegisterType("mmopb.MaskCheck_req", typeof(mmopb.MaskCheck_req));
        ProtoBuf.PType.RegisterType("mmopb.MaskCheck_ack", typeof(mmopb.MaskCheck_ack));
        ProtoBuf.PType.RegisterType("mmopb.KeyCheck_req", typeof(mmopb.KeyCheck_req));
        ProtoBuf.PType.RegisterType("mmopb.KeyCheck_ack", typeof(mmopb.KeyCheck_ack));
        ProtoBuf.PType.RegisterType("mmopb.CalculatorResultChange_req", typeof(mmopb.CalculatorResultChange_req));
        ProtoBuf.PType.RegisterType("mmopb.CalculatorResultChange_ack", typeof(mmopb.CalculatorResultChange_ack));
        ProtoBuf.PType.RegisterType("mmopb.BookStateChange_req", typeof(mmopb.BookStateChange_req));
        ProtoBuf.PType.RegisterType("mmopb.BookStateChange_ack", typeof(mmopb.BookStateChange_ack));
        ProtoBuf.PType.RegisterType("mmopb.SwitchStateChange_req", typeof(mmopb.SwitchStateChange_req));
        ProtoBuf.PType.RegisterType("mmopb.SwitchStateChange_ack", typeof(mmopb.SwitchStateChange_ack));
        ProtoBuf.PType.RegisterType("mmopb.UmberllaCheck_req", typeof(mmopb.UmberllaCheck_req));
        ProtoBuf.PType.RegisterType("mmopb.UmberllaCheck_ack", typeof(mmopb.UmberllaCheck_ack));
        ProtoBuf.PType.RegisterType("mmopb.GameIsOver_req", typeof(mmopb.GameIsOver_req));
        ProtoBuf.PType.RegisterType("mmopb.GameIsOver_ack", typeof(mmopb.GameIsOver_ack));

    }
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
